### ISSUE TITLE
Reading in dataframes

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#29]
Such a simple task.. or is it.. 

So I've been switching to read_csv from read.csv, and I went through and created lists of col_types and set those for the financial data I needed to read in. However the file has changed slightly and the coltypes are no longer valid. I don't want to continuously update those. So I removed them, however then some columns were incorrectly defined and the data dropped out (the first rows of the column were blank). 

Is there an alternative? I do think that at least the columns I want to use should be defined. However there may be other data in the file that is not necessary or not consistently in the data over different time periods. 
```
  fin_data <<- read_csv(paste0(data_store_path,"/security_financial_data.csv"), progress = F)
Parsed with column specification:
cols(
  .default = col_character(),
  company_id = col_double(),
  bloomberg_id = col_double(),
  security_icb_subsector = col_logical(),
```
And error thrown
```
See spec(...) for full column specifications.
Warning: 233354 parsing failures.
  row                        col           expected                    actual                                                                                                                             file
51010 security_icb_subsector     1/0/T/F/TRUE/FALSE General Mining            'C:/Users/clare/Dropbox (2° Investing)/PortCheck/00_Data/06_DataStore/2019Q4_export_04232020/2019Q4/security_financial_data.csv'
51010 current_shares_outstanding 1/0/T/F/TRUE/FALSE 156972432                 'C:/Users/clare/Dropbox (2° Investing)/PortCheck/00_Data/06_DataStore/2019Q4_export_04232020/2019Q4/security_financial_data.csv'
51010 free_float_percent         1/0/T/F/TRUE/FALSE 69.71114                  'C:/Users/clare/Dropbox (2° Investing)/PortCheck/00_Data/06_DataStore/2019Q4_export_04232020/2019Q4/security_financial_data.csv'
51010 free_float_shares          1/0/T/F/TRUE/FALSE 109427271.832925          'C:/Users/clare/Dropbox (2° Investing)/PortCheck/00_Data/06_DataStore [... truncated]
```
For example the security_icb_subsector should be a character type. When I use read_csv the entire outputs are then NA. 

Any help on this would be appreciated. 

This is the file
Dropbox (2° Investing)\PortCheck\00_Data\06_DataStore\2019Q4_export_04232020\2019Q4\security_financial_data.csv"

**Comment by cjyetman** [comment]
change `security_icb_subsector = col_logical()` to `security_icb_subsector = col_character()`

**Comment by cjyetman** [comment]
Sorry, I misunderstood. So you want to run `read_csv` without specifying column types? When you do that, `read_csv` will first read in **some** of the rows and guess the column types based on the data in those first rows. By default, it will read in 1000. So what's probably happening is that the first 1000 rows of `security_icb_subsector` are NA (truly), so the parser that automatically determines the column types guesses `col_logical()` for that column, because that's the most basic type that can capture a vector with all NAs.

To get around that, you could do one of the following...

1. Set the number of rows that it uses to guess to a higher number so that it captures some rows in `security_icb_subsector` that actually have data, which will enable the parser to determine a more appropriate column type. You can set it to `Inf` to make it use all rows (though it will stop at a certain point to prevent running out of memory).

`fin_data <- read_csv(paste0(data_store_path,"/security_financial_data.csv"), guess_max = Inf, progress = F)`

2. Set the columns that you know for sure explicitly, and set a default for anything else.

```
fin_data <- read_csv(paste0(data_store_path,"/security_financial_data.csv"), 
                     col_types = cols(security_icb_subsector = 'c', .default = col_guess()), 
                     progress = F)
```

3. Use `cols_only` to only import the columns you want with specified column types.

```
fin_data <- read_csv(paste0(data_store_path,"/security_financial_data.csv"), 
                     col_types = cols_only(company_id = 'c', bloomberg_id = 'c',
                                           company_name = 'c',security_icb_subsector = 'c'), 
                     progress = F)
```

**Comment by jdhoffa** [comment]
@cjyetman it looks like `read_csv` defaults to `col_guess()` if you only specify certain `col_types()` by name? 

``` r
library(readr)

fake_data <- tibble::tribble(
  ~column1, ~column2, ~column3, ~column4,
      TRUE,       1L,        1,    "dog",
     FALSE,       2L,      0.5,    "cat",
     FALSE,       3L,      2.5,    "big",
      TRUE,       4L,      0.2,    "bat"
  )

temp_path <- glue::glue(tempdir(),"fake_data.csv")

readr::write_csv(fake_data, temp_path)

# specify some columns by name, and readr guesses the rest by checking the first 1000 rows
col_specifications <- cols(column1 = col_logical(),
                           column4 = col_character())
read_in_data <- readr::read_csv(temp_path, col_types = col_specifications)
```

<sup>Created on 2020-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cjyetman** [comment]
@jdhoffa Yes, but you can specify the default, i.e. `.default = 'c'`. Or you can use `cols_only` to specify the columns you want and skip the rest.

**Comment by Clare2D** [comment]
Thanks guys, that was useful. Implemented now.
