### ISSUE TITLE
Stress Test Failing art

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#325]
When no portfolio data is available, the stress test functions give this error. Not critical.

`-- web_tool_script_2.R ---------------------------------------------------------
Loading PACTA.analysis
[1] "No Equity Portfolio Data available. Skipping!"
[1] "No Bonds Portfolio Data available. Skipping!"
Loading PACTA.analysis
[1] "No Bonds Portfolio Data available. Skipping!"
[1] "No Bonds Portfolio Data available. Skipping!"

-- web_tool_script_3.R ---------------------------------------------------------
Error in eval_tidy(xs[[j]], mask) : object 'NA_comp_' not found`

**Comment by jacobvjk** [comment]
@Clare2D since the part of this issue that clearly addresses the stress test (same warning about Bonds twice in a row, when one should clearly be about equity) has been solved in https://github.com/2DegreesInvesting/StressTestingModelDev/pull/97
I suggest closing this issue.

This does most likely NOT solve the error from webtool script 3, `Error in eval_tidy(xs[[j]], mask) : object 'NA_comp_' not found` but this would require a reprex or similar (at least the user id for which this error occurred)

**Comment by cjyetman** [comment]
`NA_comp_` does not exist.... I would guess that somewhere a blank tibble is being created with a column which was intended to be `NA_complex_` (probably `NA_real_` would be better)

**Comment by Clare2D** [comment]
That's a similar thought to what I had @cjyetman after making that change last night :)

**Comment by jacobvjk** [comment]
exactly, but this message does not show which tibble that might be or which user id this relates to. If I get either of those, I'm happy to look into it

**Comment by jacobvjk** [comment]
And searching the repo for NA_comp(lex)_ does not yield more insight

**Comment by cjyetman** [comment]
Yeah, I did the same thing @jacobvjk and didn't find anything... maybe that came from an on-the-fly fix that @Clare2D made?

**Comment by Clare2D** [comment]
🤦 Found it. It's real now. No longer an issue...
