### ISSUE TITLE
Update currency file with 2020Q4

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#394]
We need to get the currency data for 31. Dec 2020 for the currencies listed in the currencies.rda file in PACTA_Analysis/data. I've created a xls of this for ease.
[Currencies.xlsx](https://github.com/2DegreesInvesting/PACTA_analysis/files/5988332/Currencies.xlsx)
 This then needs to be saved in the correct format ready for use. Ie the conversion factor for the currency to USD
This data I believe already comes through the financial _data and can either be obtained from there or on a website online.
@catarinabrg can you download this data? and @cjyetman can you help her get the file formatted correctly? Perhaps this should just be permanently saved as a csv for simplicity.

**Comment by cjyetman** [comment]
I was just looking into this the other day coincidentally... but I didn't know where we source the data from, or certain decisions about it (like do we take the average for a quarter, or the rate on the last day, or the first day, or?). I came up with this for pulling historical data from ECB, but it doesn't cover all of the currencies we have in the current file...
``` r
library(readr)
library(dplyr)
library(tidyr)

url <- "http://www.ecb.int/stats/eurofxref/eurofxref-hist.zip"
zipfile <- tempfile(fileext = ".zip")
download.file(url, zipfile)

read_csv(zipfile, na = "N/A", col_types = cols(.default = col_double(), Date = col_date())) %>%
  filter(as.POSIXlt(Date)$year + 1900 > 2015) %>%
  mutate(Date = paste0("ExchangeRate_", format(Date, format = "%Y"), quarters(Date))) %>%
  pivot_longer(c(-Date, -USD), values_drop_na = TRUE) %>%
  group_by(Date, name) %>%
  summarise(value = mean(USD) / mean(value), .groups = "drop") %>%
  pivot_wider(names_from = Date, values_from = value) %>%
  rename(Currency_abbr = name)
```

**Comment by cjyetman** [comment]
since we use the exchange rate on the last day of the quarter, I updated the above script...
``` r
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)

url <- "http://www.ecb.int/stats/eurofxref/eurofxref-hist.zip"
zipfile <- tempfile(fileext = ".zip")
download.file(url, zipfile)

read_csv(zipfile, na = "N/A", col_types = cols(.default = col_double(), Date = col_date())) %>%
  filter(year(Date) > 2015) %>%
  group_by(quarter = paste0("ExchangeRate_", year(Date), quarters(Date))) %>% 
  filter(Date == max(Date)) %>% 
  ungroup() %>% 
  mutate(EUR = 1) %>% 
  select(-Date, -X43) %>% 
  pivot_longer(c(-quarter, -USD), names_to = "currency", values_drop_na = TRUE) %>% 
  mutate(value = value / USD, .keep = "unused") %>% 
  pivot_wider(names_from = quarter, values_from = value) %>% 
  arrange(currency)
```

**Comment by Clare2D** [comment]
Incredible! We should start a document/information point somewhere that outlines the steps for what needs to happen when we get new quarterly data, perhaps an Rmd with this content included. 
Why is EUR=1?

**Comment by cjyetman** [comment]
`mutate(EUR = 1) %>% ` is because the ECB provides exchange rates from/to Euros, and I think we use USD as the base, so I essentially add the EUR currency, which should always be 1 to 1 to itself, before converting using USD as a denominator.

**Comment by Clare2D** [comment]
To complete this, are you able to pass this file through to replace the other files? No rush.

**Comment by cjyetman** [comment]
> but it doesn't cover all of the currencies we have in the current file...

 @Clare2D is that a concern?

**Comment by Clare2D** [comment]
Yeah unfortunately. :(

**Comment by cjyetman** [comment]
do you know what the source is for the current dataset?

**Comment by Clare2D** [comment]
Not really. We generally just obtain this from the first google result, and have continually increased the coverage over time. The other option would be to use the security financial data, as I believe the currency data is also being passed from there, we could use that to add to this file..

**Comment by cjyetman** [comment]
ok... I'd feel most comfortable with choosing a consistent, reputable source and writing a short scraper/getter for it... maybe I'll ask on Slack for ideas

**Comment by cjyetman** [comment]
I created a script to get currency data from IMF's API over in the [data-steward-handover repo](https://github.com/2DegreesInvesting/data-steward-handover/tree/master/currency_exchange_rates)

that script probably can achieve the goal here

**Comment by cjyetman** [comment]
@jdhoffa opinion on this?

Current situation is (as far as I understand)...
1. when using the web tool scripts, the built-in [currencies.rda](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/data/currencies.rda) (or [currencies.rds](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/data/currencies.rds)) file only gets used if `new_data == TRUE` here, which I do not know of any use cases anymore where that should happen, because I'm always guiding people to point to the pacta-data repo for their data which has its own currency data, and one would have to modify the one of the "WebParameters" files ([here](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/parameter_files/WebParameters_2dii.yml) or [here](https://github.com/2DegreesInvesting/PACTA_analysis/blob/master/parameter_files/WebParameters_docker.yml)) with `new_data: TRUE` to trigger the `new_data == TRUE` branch https://github.com/2DegreesInvesting/PACTA_analysis/blob/3f02896e149148db3283ee673164ea0892438227/web_tool_script_1.R#L47
2. the pacta-data repo currently provides its own currency data (created with [the scraper script](https://github.com/2DegreesInvesting/data_preparation/blob/master/get_currency_exchange_rates.R) in data_prep which pulls historical currency data for the appropriate quarter/s from the IMF api)
3. "offline" or whatever version of PACTA probably does require the `data/currencies.rda` file here, but I think we're moving towards aggressively deprecating/discouraging that

So I would be in favor of saying this issue should be closed and we don't need to bother maintaining duplicate versions of this currency data. Do you agree?

**Comment by jdhoffa** [comment]
Agree!
