### ISSUE TITLE
Presenting results seems beyond the scope of PACTA_analysis

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#417]
PACTA_analysis currently deals with presenting results but this seems out-of-scope.

> Personally, I would like to detach this 3rd step from the process in the future. What I imagine is that running the PACTA analysis generates results (meaning data that has been merged and certain calculations done) based on the input portfolio and various options. After that, a user (or web server) may want to use those results to generate an interactive report, or maybe an Executive Summary PDF, or maybe just one interactive alignment plot, or maybe just do some manual analysis with it in R, or maybe some combination of those. But that's the point where users branch out into different things.

-- https://github.com/2DegreesInvesting/PACTA_analysis/pull/408#discussion_r586227331

It also adds  system requirements and dependencies on PACTA "siblings" (https://github.com/2DegreesInvesting/PACTA_analysis/pull/408#discussion_r586229854).

**Comment by cjyetman** [comment]
looking back at this, I need to clarify...

I still believe that "running PACTA" should not necessarily include the final production of a report or graphic or whatever, because what one wants to do with the results is not always the same. However, this "3rd step" is a 100% necessary part of what the web tool does, so... unless/until we begin maintaining the full chain of steps needed for the web tool somewhere else, this repo (PACTA_analysis) does necessarily include that step.

**Comment by cjyetman** [comment]
Not sure exactly what the intent was for this issue, but #480 at least separates the PACTA process from the stress testing and create_interactive_report stuff. Now web tool scripts 1 and 2 do the PACTA stuff, and web tool script 3 does only the do-stuff-with-PACTA-results stuff

**Comment by maurolepore** [comment]
Nice to note moved towards a cleaner state. Feel feel to close.
