### ISSUE TITLE
Save/export switch in build_with_tag.sh doesn't seem to work

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/PACTA_analysis#616]
The "save" switch/option never seems to work for me as expected when I do e.g. `./build_with_tag.sh -s -t 0.3.3`. Any ideas @AlexAxthelm @maurolepore?

https://github.com/2DegreesInvesting/PACTA_analysis/blob/dfa27446159a649fb5b840eff1da7d128d875d1a/transitionmonitor_docker/build_with_tag.sh#L12-L13

https://github.com/2DegreesInvesting/PACTA_analysis/blob/dfa27446159a649fb5b840eff1da7d128d875d1a/transitionmonitor_docker/build_with_tag.sh#L22

https://github.com/2DegreesInvesting/PACTA_analysis/blob/dfa27446159a649fb5b840eff1da7d128d875d1a/transitionmonitor_docker/build_with_tag.sh#L172-L180

**Comment by AlexAxthelm** [comment]
@cjyetman I'd suggest not using `OPTARG` in this line, since this is a logical flag, not one that requires options. see the `-v` and `-i` flags in the run-like-constructiva script https://github.com/2DegreesInvesting/PACTA_analysis/blob/dfa27446159a649fb5b840eff1da7d128d875d1a/transitionmonitor_docker/run-like-constructiva-flags.sh#L49

**Comment by maurolepore** [comment]
I'll go with Alex's suggestion. My bash skills are rusty :-(
