### ISSUE TITLE
`PACTA_analysis` removes the dependency on bbg_id

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/PACTA_analysis#634]
lgtm. Does there need to be an equivalent PR in `PACTA_analysis` which removes the dependency on bbg_id?

_Originally posted by @jdhoffa in https://github.com/2DegreesInvesting/pacta.data.preparation/pull/18#pullrequestreview-1061471067_

**Comment by cjyetman** [comment]
I'm working on this in branch https://github.com/2DegreesInvesting/PACTA_analysis/tree/pacta_v2022_v2

It will be a part of a much larger set of changes.

**Comment by jdhoffa** [comment]
I can start PR's into that branch, if there's anything you would like me to work on.

**Comment by cjyetman** [comment]
At this point, I just need the new format outputs of data_prep so I can integrate them. I already cleaned up things dramatically. Actually, if you wanted to, you could go through all the scripts in `R/` and get rid of ones that are not being used at all.

**Comment by cjyetman** [comment]
2DegreesInvesting/pacta.data.preparation/issues/19

**Comment by cjyetman** [comment]
this issue is only relevant to the new 2021Q4 version

pretty sure this has already been mostly achieved through...
https://github.com/2DegreesInvesting/PACTA_analysis/commit/e0bf478b9bbcb33c92da1a742c7035cbed8de8c4
https://github.com/2DegreesInvesting/PACTA_analysis/commit/51e995a32b843bac03ee91cdb5d9c25eaa91fc12
