### ISSUE TITLE
Move calculation of portfolio weights to the first input check step 

### ISSUE THREAD

**Issue by Clare2D** [2DegreesInvesting/PACTA_analysis#68]
To get the portfolio weights for E4I from the first step; we should move this to the portfolio_input_check particularly in the web tool

**Comment by Clare2D** [comment]
Not urgent, but important for the webtool.

**Comment by Clare2D** [comment]
@2diiKlaus 
As discussed with Klaus, we just need one output for the CAG - it would be a dataframe with company_id and portfolio weight saved as something relevant coming out of web_script_1.

**Comment by jacobvjk** [comment]
@Clare2D am I right to assume that want this to be consistent between the web_tool and the offline tool?
At first glance, I would do the following:
- split up the loop in `3_run_analysis.R` over investors, so that we can move the first part that calculates the pf_weights (and ownership weights? would be consistent) to the prior script (`2_project_input_analysis.R`).
- The corresponding changes from script 2 to script 1 would be made for the webtool
- the resulting data frames are written to an external destination, e.g. the 30_Processed_Inputs folder in the format required.
- this could be optional, but it might be better to have this mandatory, so the analysis can still read this data from file and therefore run as a (almost) standalone script, without having to run the preprocessing script every time.
Any opinion on that?

**Comment by Clare2D** [comment]
Isn't the online tool looping over portfolio rather than investor? I would assume this almost doesn't matter as the group_by should do the grouping anyway? I think this function can be moved almost as is to the script 1 & 2_project_input_analysis, but agree that it should be moved for both for consistency. 
Output data frames to 30_proc_inputs is correct 

I don't get your final point though..

**Comment by jacobvjk** [comment]
final point was about always writing those files to 30_Processed_Inputs or optionally writing them there. Which only is optional if both scripts are run in the same session of course, so I suggest we just ignore my last point

**Comment by jacobvjk** [comment]
And no, the webtool is not looping over portfolios. We removed that again, because every run will either be a single PF or a merged PF in the webtool. The loop over investors does not do anything in the webtool as it is always just 1 investor, but the functions were copied from the offline tool as is. therefore there still is a loop and I would prefer to keep it somewhat in sync with the way it's run in master.

**Comment by Clare2D** [comment]
Ok that makes sense!

**Comment by Clare2D** [comment]
Wir würden dafür das Total Portfolio nehmen und dann daraus die folgenden Spalten nutzen:
company_id
portfolio_weight (das ist ja aktuell noch nicht Teil der Datei soweit ich das sehe)
Aktuell ist das total_portfolio auch nur als rda verfügbar, Wim würde es bevorzugt als json Datei bekommen
Soweit wie ich das sehe müssen dafür 2 Dinge getan werden:
die portfolio_weights müssen berechnet und ausgegeben werden
 der output sollte als json verfügbar sein

@2diiKlaus
