### ISSUE TITLE
The workflow to generate a report with the web tool

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/PACTA_analysis#82]
I'm trying to understand the workflow to generate a report with the web tool, including both existing processes and processes that we would like to develop in the near future. This flow chart reflects my current understanding. Can you please review it and correct it as necessary?: https://bit.ly/2ZL6vfP.

![image](https://user-images.githubusercontent.com/5856545/93351075-e3926f00-f7fe-11ea-88ff-4f150d6bbc4b.png)

I'm particularly unclear on how the code in the repo create_interactive_report/ works. I need to understand where the text for each chapter comes from and goes to; this is important for me to assess how feasible it is to adapt the code to meet the goals you suggested recently: (a) use multiple templates, and (b) output a bookdown structure.

I could dig deeper into the code and try figure it out, but I suspect some of you -- ideally @cjyetman -- already know it well enough to explain it to me. Maybe we could arrange a call?

**Comment by cjyetman** [comment]
There's a video in Dropbox somewhere of the 2nd part of the tutorial on this that I gave in the Berlin office in my last few days. I strongly suggest seeking that out and watching it.

In short though, practically everything needed is a parameter that is passed to the `create_interactive_report()` function, e.g. the text template, the data, etc., so it's less of a question of "where" it comes from (because one must explicitly specify where it exists when calling the function), and more of a "what" can they be kind of question, which is not well documented.

The text generally comes from whichever HTML file template is specified, which is typically the result of rendering an Rmd file, e.g. the one found at https://github.com/2DegreesInvesting/create_interactive_report/blob/master/template_beta/template.html

That HTML template hypothetically could be made in any way one sees fit to generate an HTML file, however that one specifically was created by rendering the Rmd found here https://github.com/2DegreesInvesting/create_interactive_report/tree/master/template_beta_maker

**Comment by Clare2D** [comment]
I think we worked this one out!
